baseURL = "https://JoshPadnick.com/"
languageCode = "en-us"
title = "Josh Padnick"

# Show 10 posts per page
paginate = 10

# If a post doesn't have a <!--more--> entry, just display the whole thing.
summaryLength = 5000

googleAnalytics = "UA-1640976-3"

disqusShortname = "joshpadnick"

[permalinks]
  post = "/:year/:month/:day/:title/"
